# Generated by Django 2.2.1 on 2019-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_auto_20190513_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Почта'),
        ),
    ]
