# Generated by Django 2.2.1 on 2019-05-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_auto_20190513_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Почта'),
        ),
    ]
