# Generated by Django 2.2.1 on 2019-05-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0005_auto_20190513_0929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
    ]
